### ISSUE TITLE
Locations issues with switching between Zipcodes and countries when modifying search

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#186] opened 2019-12-27 19:51 UTC
Steps to Reproduce this issue:
1. Do a zipcode search for 20850
2. On the results page, click modify search, and go back and select a country (like Poland), and then submit
3. One results page, modify search again, and select another country (like Israel), and submit again. Note that this 3rd search for Israel returns my original zipcode search for 20850

**Comment by sarinapadilla** [comment] 2023-08-30 18:42
Cannot reproduce this issue, so closing this ticket.

**Closed by sarinapadilla** 2023-08-30 18:42 UTC
