### ISSUE TITLE
Getting error message on the modal and error 500 on the console on trying to print a trial 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-search-app#305] opened 2021-09-20 18:49 UTC
### Issue description
On trying to print the trial returned by https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?a=90&loc=0&rl=1&t=C3992 (only one result is returned) we are getting an error message  on the modal and error 500 on the console.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?a=90&loc=0&rl=1&t=C3992
2.  Select the trial you want to Print (only one result is returned)
3. We get the error message on the modal and error 500 is returned on the console.

### What's the expected result?
- user should be able to go to the Print page

### What's the actual result?
- User is getting an error message in the modal and error 500 in the console.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/134057878-9870310a-8d5c-436f-b64f-ba67e237a5b5.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment] 2022-07-21 20:28
I am not able to reproduce this issue. Since this is a pretty old bug, I'm going to close this ticket.

**Closed by sarinapadilla** 2022-07-21 20:28 UTC
Labels: bug
